stages:
  - docker
  - deploy

image: docker:latest

docker:
  stage: build
  script:
    - docker login -u "gitlab-ci-token" -p "$CI_BUILD_TOKEN" $CI_REGISTRY
    - docker build --pull -t "$CI_REGISTRY_IMAGE:latest" .
    - docker push "$CI_REGISTRY_IMAGE:latest"

Gitlab:
  stage: deploy
  image: docker:latest
  script:
    - docker login -u "gitlab-ci-token" -p "$CI_BUILD_TOKEN" $CI_REGISTRY
    - docker build --pull -t "$CI_REGISTRY_IMAGE:latest" .
    - docker push "$CI_REGISTRY_IMAGE:latest"

Github:
  stage: deploy
  image: alpine
  script:
    - apk update && apk --no-cache add git
    - git push "https://$github_repo_user:$github_repo_pw@github.com/Gmentsik/docktartar.git" HEAD:master
  only:
    - stable