version: '2'

services:
  docktartar:
    image: gmentsik/docktartar
    environment:
      BACKUP_PERIOD: 24h
      BACKUP_DELAY: 5s
      TIMEZONE: "Europe/Vienna"
      LOOP: 'true'
      TAG: 'docker'
      TAR_OWNER_USERID: 0
      TAR_OWNER_GROUPID: 0
      STOP_CONTAINERS: "all"
      START_CONTAINERS: "all"
    volumes:
    - /srv/docker:/backupSource
    - /var/backup/docker:/backupTarget
    - /var/run/docker.sock:/var/run/docker.sock
    - /var/lib/docker:/var/lib/docker
    stdin_open: true
    network_mode: none
